apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder
  namespace: resume-builder
  labels:
    app: resume-builder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-builder
  template:
    metadata:
      labels:
        app: resume-builder
    spec:
      containers:
        - name: resume-builder
          image: nhat416/resume-builder:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resume-builder-secret
                  key: DATABASE_URL
